#!/bin/sh
#
# abook export script to sync abook & mutt/alias by armin wolfermann

addressbook=~/Bbox/addressbook.abook
abook --datafile $addressbook ${@}
abook --convert \
	--informat abook --infile $addressbook \
	--outformat mutt --outfile ~/.config/mutt/alias.new
mv ~/.config/mutt/alias ~/.config/mutt/alias.bak
mv ~/.config/mutt/alias.new ~/.config/mutt/alias

