#!/bin/sh

# mandoc passes a file name, other tools write to stdout
# using `cat "$@"` we take care of both reading from file and stdin
# https://github.com/sharkdp/bat/issues/1145#issuecomment-1743518097
exec cat "$@" | col -bx | bat --language man --style plain --pager "$PAGER"
