#!/bin/bash

MBOX_TMPFILE="$HOME/Maildir/.geraldine_mbox.tmp"
MAILDIR="$HOME/Maildir"

set -e

function fetchmail()
{
    if [[ -s "$MBOX_TMPFILE" ]]; then
        echo "Running fdm early to process leftover files in $MBOX_TMPFILE"
        fdm -f "$MAILDIR/fdm.conf" -a "geraldine" fetch
    fi
    if [[ -s "$MBOX_TMPFILE" ]]; then
        echo "ERROR: fdm did not process all messages in $MBOX_TMPFILE" >&2
        exit 1
    fi

    echo "Transferring mbox from geraldine.fjfi.cvut.cz"
    messages=$(ssh geraldine '$HOME/.local/bin/messages -q')
    if [[ "$messages" != "0" ]]; then
        # NOTE: movemail supports locking
        ssh geraldine '$HOME/.local/bin/movemail /var/mail/klinkovsky $HOME/mbox'
        scp -Cq geraldine:mbox "$MBOX_TMPFILE"
        ssh geraldine 'rm $HOME/mbox'
    fi

    fdm -f "$MAILDIR/fdm.conf" fetch

    # synchronize with jlk.fjfi.cvut.cz
    if [[ $(uname -n) != *".fjfi.cvut.cz" ]]; then
        echo "Synchronizing maildir with jlk.fjfi.cvut.cz"
        unison maildir -batch -silent -log=false
    fi

    # synchronize calendars, tasks, contacts
    vdirsyncer sync
}

# check online
check_domain=ping.archlinux.org
if ! ping -c 1 "$check_domain" > /dev/null; then
    echo "$check_domain is not reachable, check your network status."
    exit 1
fi
check_host=10.13.0.1
if ! ping -c 1 "$check_host" > /dev/null; then
    echo "$check_host is not reachable, check the host status or WireGuard network."
    exit 1
fi

# synchronize metadata (displayname, color)
vdirsyncer metasync

if [[ "$1" == "loop" ]]; then
    # ring a bell when the loop breaks
    trap 'echo $(tput bel)' EXIT

    while true; do
        fetchmail
        sleep 2m
    done
else
    fetchmail
fi
