#!/bin/bash

# dumb wrapper to get the password for remote mailboxes

account="$1"
passwdfile="$HOME/.config/mutt/password-$account.gpg"

if [[ -f "$passwdfile" ]]; then
    gpg --quiet --batch --use-agent --decrypt --output - "$passwdfile"
else
    echo "error: file $passwdfile does not exist." >&2
    exit 1
fi
