#! /usr/bin/env python

import os
import sys
import re
import subprocess

from pyalpm import vercmp

db_path = "jlk.db.tar.xz"
pkgname_regex = re.compile("^(?P<pkgname>[a-z0-9@._+-]+)-(?P<pkgver>[a-z0-9._:]+)-(?P<pkgrel>[a-z0-9._:]+)-(?P<arch>any|x86_64|i686)\.pkg\.tar(\.xz|\.zst)?$", re.IGNORECASE)

if __name__ == "__main__":
    path = os.path.expanduser("~/build/pkgs/")
    assert os.path.isdir(path)
    os.chdir(path)

    current_packages = {}
    old_pkgnames = set()
    old_files = set()

    # remove files that don't match pkgname_reges from further processing!!
    for f in os.listdir():
        if not os.path.isfile(f):
            continue
        match = re.match(pkgname_regex, f)
        if match:
            pkgname = match.groupdict()["pkgname"]
            pkgver = match.groupdict()["pkgver"]
            pkgrel = match.groupdict()["pkgrel"]

            data = match.groupdict()
            data["fname"] = f
            current_packages.setdefault(pkgname, data)

            cur_pkgver = current_packages[pkgname]["pkgver"]
            cur_pkgrel = current_packages[pkgname]["pkgrel"]
            comp = vercmp(pkgver + "-" + pkgrel, cur_pkgver + "-" + cur_pkgrel)
            if comp < 0:
                old_pkgnames.add(pkgname)
                old_files.add(f)
            elif comp > 0:
                current_data = current_packages[pkgname]
                old_pkgnames.add(current_data["pkgname"])
                old_files.add(current_data["fname"])
                current_packages[pkgname] = data

    # update database entries
    to_update = set()
    for pkgname, data in current_packages.items():
        if pkgname in old_pkgnames:
            to_update.add(data["fname"])
    if to_update:
        cmd = ["repo-add", "-n", "-s", db_path, *sorted(to_update)]
        subprocess.run(cmd, check=True)
    else:
        print("No packages to update.")

    # remove old files
    for f in sorted(old_files):
        print("Deleted: %s" % f)
        os.remove(f)
        if os.path.isfile(f + ".sig"):
            print("Deleted: %s" % f + ".sig")
            os.remove(f + ".sig")
