#!/bin/bash

host="$1"

if [[ "$host" == "" ]]; then
    echo "usage: $0 [user@]hostname"
    exit 1
fi

hostname=$(ssh "$host" "hostname")
port=11111

if [[ "$hostname" == "teslon" ]]; then
    ssh -C -t -L "localhost:11111:$hostname:$port" "$host" "bash -lc 'module load mpi/openmpi3-x86_64 paraview/5.6.0 && mpirun -np 4 pvserver -display :0 --server-port=$port'"
#elif [[ "$hostname" == "gp2.fjfi.cvut.cz" ]]; then
#    ssh -C -t -L "localhost:11111:$hostname:$port" "$host" "bash -lc 'module load ParaView/5.6.1-osmesa-bin && mpiexec -np 4 pvserver -display :0 --server-port=$port'"
else
    ssh -C -t -L "localhost:$port:$hostname:$port" "$host" "mpirun -np 2 pvserver -display :0 --server-port=$port"
fi
