#! /bin/bash

function get_pkgdesc()
{
    local path="$1"
    if [[ ! -f "$path/PKGBUILD" ]]; then
        if [[ -f "$path/trunk/PKGBUILD" ]]; then
            path="$path/trunk"
        else
            return 0
        fi
    fi

    pushd "$path" > /dev/null
    if [[ -f ".SRCINFO" ]]; then
        cat .SRCINFO | awk -F "=" '/pkgdesc/ {print $2}' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
    else
        makepkg --printsrcinfo | awk -F "=" '/pkgdesc/ {print $2}' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
    fi
    popd > /dev/null
}

for path in "/srv/http/git/"*/*; do
    pushd "$path" > /dev/null
    pkgname=$(basename "$path")
    pkgdesc=$(get_pkgdesc "$path")
    if [[ "$pkgdesc" != "" ]]; then
        git config --local gitweb.description "$pkgdesc"
    fi
    popd > /dev/null
done

for path in "/srv/http/git/abs/"*; do
    pkgname=$(basename "$path")
    pushd "$path" > /dev/null
    git config --local gitweb.homepage "https://www.archlinux.org/packages/?name=$pkgname"
    popd > /dev/null
done

for path in "/srv/http/git/"{aur,aur_mine}/*; do
    pkgname=$(basename "$path")
    pushd "$path" > /dev/null
    git config --local gitweb.homepage "https://aur.archlinux.org/packages/$pkgname/"
    popd > /dev/null
done
